### ISSUE TITLE
As a person monitoring their eating, I want to take a survey that takes my height, weight and weight goals on my first login, so that I can find my target calories and macros.

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#5]
**Acceptance Tests:**

_Test 1_
1.) Go to the [login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) and click signup.
![signup_highlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/df90c21c-e255-4bd3-9860-91e8b98fdd07)
2.) Create a new account and write down the username and password. Click the link to the login page at the bottom of the signup sheet and enter these credentials. 

![login_redirhighlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/b3b1922f-df61-4730-91eb-a20dc9d25c61)
You should be presented with the initial survey after signing in for the first time.
![survey_redirect.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/eb5a2e00-1fe5-47c8-9c5b-d91d4b03485a)

3.) Click the drop down menu for "What is your sex?" 
4.) Ensure three options drop down and the options are Male, Female, and Other/Prefer Not To Say
5.) Click the drop down menu for "What fitness goal best highlights what you're trying to achieve?"
6.) Ensure three options drop down and the options are Lose Weight/Cut, Gain Weight/Bulk, and Maintain
7.) Click each macro button under "What food macros are you looking to center recommendations' around? (If Any)"
8.) Ensure each button does not update the page and only one can be selected at a time.
9.) Look for the height and weight input boxes and try entering letters and any other special characters.
10.) Ensure letters and special characters are disallowed, except for the letter e.
11.) Look for the height and weight input boxes and enter more than three numbers into each of them.
12.) Fill out the rest of the fields on the page and then click the "Get Started" button.
13.) Ensure an error message pops up near the height and weight buttons stating the values are out of range.
14.) Look for the area to select a macro.
15.) Ensure only one macro can be selected at a time.
16.) Look for the area to enter activity level and enter any number greater than seven or less than one.
17.) Fill out the rest of the fields on the page and then hit the "Get Started" button.
18.) Ensure an error message pops up near the activity level field stating the value is out of range. After this Test 1 is complete but do not leave the survey page, you will need to be on it for the next test. 

_Test 2_
1.) Properly fill each field but leave one or two fields blank.

2.) Click the "Get Started" button at the end of the page

3.)  Ensure an error message appears requiring you to fill in the empty field.

_Test 3_

1.) Properly fill each field in on the page

2.)  Click the "Get Started" button at the end of the page

3.) Ensure the button redirects the user to the content page
![chad_content.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/194eb8ec-002f-4053-84f2-33ca60457cca)

**Comment by Nildham21** [comment]
All these tests should be combined into one as all of these fields need to be filled in order for the survey to be submitted. 

Add a test that **requires all the input fields to be filled in** and detail what happens when the get started button is clicked

Add a test that **requires one or more input fields to be not filled in** and detail what happens when the get started button is clicked

**Comment by Nildham21** [comment]
Now that we have login sessions, without a user directly logging in they will not be able to access the survey page unless they create a new account and are logging in for the first time. Please update your tests such that it requires the untrained user to first create a new account, log in for the first time and then detail all the steps to fill out the survey. You need to include a test of what happens if a user attempts to submit without filling out all the fields

**Comment by Nildham21** [comment]
The same feedback from #35 can be applied here

**Comment by Nildham21** [comment]
Add sprint 4 label
