### ISSUE TITLE
add meal name to content page

### ISSUE THREAD

**Issue by JakeGuzzardo** [cse442-at-ub/project_s23-the-ai-violators#71]
**Task Tests**

_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )![log.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/83a7517c-95d0-41d6-9770-747e83a4196b)

2. Login in with test username `j` and password `string` and verify you were redirected to the content page ![cont.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/7e83bf5c-4a03-4ed3-9e43-212d7cf6a9bd)

3.  Click the link to the Track page on the top of screen in the nav bar and verify you are directed to the following page![track.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/a99ba915-bcf4-4d1e-a6e0-0728a8af0d06) 
4. type TESTFOOD under meal
5. Select todays date under date
6. Put the values 4 5 and 6 for carbs protein and fats respectively 
7. Enter 100 for calories. Here is an example screenshot of the filled out form![formfill.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/308de46b-b89d-49cd-9ba7-f7b334ec8f42) 
8. press Enter or click add and go back to content page
9. Verify the meal name is now displayed next to the food items for the day as shown![snip.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/1e787659-2e0b-4f94-ade8-925421e9d1f8)

**Comment by Nildham21** [comment]
Instead of having directions such as "verify you were redirected to the Content Page", and providing a link, can you please attach a screenshot of what the content page looks like so they can verify they are on the right page? 

The same applies to the track page. 

Step 7, how do they go back to the content page? What should they click to return to the content page? Please be more clear.

Step 8, since you gave the user a specific value to enter for the meal name when they verify they should be checking for this value in the meal name section. Be specific in what the meal name should be when they check
